### ISSUE TITLE
Use of path("") is discouraged

### ISSUE THREAD

**Issue by jrudolph** [hseeberger/reactive-flows#8]
The behaviour of path changed changed slightly with the spray 1.0 release. `path("")` now only works on the top-level. It has a complete section in the documentation explaining the reasoning, see "PathMatcher infrastructure" in http://spray.io/project-info/migration-from-M8/#big-breaking-changes

**Comment by hseeberger** [comment]
Thanks for the hint.
Looking at the docs I thought that path(Slash) might work, but it doesn't, because it seems that the leading slash isn't part of the path (matcher). Why?
What exactly should I use to match `127.0.0.1:9001/` or `127.0.0.1:9001`?

**Comment by jrudolph** [comment]
`path` already matches a prefixing slash. So, you need to use `pathSingleSlash` on the root level (see below) and one of `pathEnd`, `pathSingleSlash`, or `pathEndOrSingleSlash`.

`http://127.0.0.1:9001` is a bit tricky: this is potentially a valid general URI but the empty path is not allowed for a request (you need to put something between method and http version in `GET / HTTP/1.1` as explained in http://tools.ietf.org/html/rfc7230#section-5.3.1). So for a request the empty path version is interpreted as a path with just an empty slash.

**Comment by hseeberger** [comment]
Ah, OK. `pathSingleSlash` works fine. 
What do you mean with "one of `pathEnd` ..."?

**Comment by jrudolph** [comment]
Ah, the end of the sentence is missing...

I meant, you would choose one of those when matching on nested levels, i.e. not on the root level, depending on whether you want to mean `/abc` and `/abc/` should mean the same or which one you want to support.
